# Generated by Django 4.2 on 2023-04-18 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('num_of_pages', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, default=2023, null=True)),
                ('genre', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('0', 'Nėra'), ('1', 'Užsakyta'), ('2', 'Yra')], default=0, max_length=1)),
                ('authors', models.ManyToManyField(to='author.author')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
