# Generated by Django 4.2 on 2023-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='number_of_books',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='rewards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
