# Generated by Django 4.2 on 2023-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_born_author_country_author_number_of_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
